# Generated by Django 2.1.5 on 2019-02-08 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='ticket',
            new_name='relationship',
        ),
    ]
