# Generated by Django 2.1.5 on 2019-02-08 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0003_student_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
    ]
