# Generated by Django 2.1.5 on 2019-02-04 15:10

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20190204_2259'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', user.models.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
